// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pico2WH.Pi5.IIoT.Infrastructure.Persistence.Context;

#nullable disable

namespace Pico2WH.Pi5.IIoT.Infrastructure.Migrations.Dev
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260412123923_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dev")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pico2WH.Pi5.IIoT.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("device_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("DeviceIdentifier")
                        .IsUnique()
                        .HasDatabaseName("ix_devices_device_id");

                    b.ToTable("devices", "dev");
                });

            modelBuilder.Entity("Pico2WH.Pi5.IIoT.Domain.Entities.DeviceControlAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Accepted")
                        .HasColumnType("boolean")
                        .HasColumnName("accepted");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("command");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("device_id");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_id");

                    b.Property<Guid?>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<int>("Value16Bit")
                        .HasColumnType("integer")
                        .HasColumnName("value_16bit");

                    b.Property<int>("ValuePercent")
                        .HasColumnType("integer")
                        .HasColumnName("value_percent");

                    b.HasKey("Id")
                        .HasName("pk_device_control_audits");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_device_control_audits_request_id");

                    b.ToTable("device_control_audits", "dev");
                });

            modelBuilder.Entity("Pico2WH.Pi5.IIoT.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("token_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("revoked_reason");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", "dev");
                });

            modelBuilder.Entity("Pico2WH.Pi5.IIoT.Domain.Entities.TelemetryReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("Co2Ppm")
                        .HasColumnType("double precision")
                        .HasColumnName("co2_ppm");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("DeviceTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("device_time");

                    b.Property<double?>("HumidityPct")
                        .HasColumnType("double precision")
                        .HasColumnName("humidity_pct");

                    b.Property<double?>("HumidityPctScd41")
                        .HasColumnType("double precision")
                        .HasColumnName("humidity_pct_scd41");

                    b.Property<bool>("IsSyncBack")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sync_back");

                    b.Property<double?>("Lux")
                        .HasColumnType("double precision")
                        .HasColumnName("lux");

                    b.Property<bool?>("PirActive")
                        .HasColumnType("boolean")
                        .HasColumnName("pir_active");

                    b.Property<string>("RawPayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<DateTime>("ServerTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("server_time");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("site_id");

                    b.Property<double?>("TemperatureC")
                        .HasColumnType("double precision")
                        .HasColumnName("temperature_c");

                    b.Property<double?>("TemperatureCScd41")
                        .HasColumnType("double precision")
                        .HasColumnName("temperature_c_scd41");

                    b.HasKey("Id")
                        .HasName("pk_telemetry_records");

                    b.HasIndex("DeviceId", "DeviceTimeUtc")
                        .HasDatabaseName("ix_telemetry_records_device_id_device_time");

                    b.HasIndex("DeviceId", "DeviceTimeUtc", "IsSyncBack")
                        .IsUnique()
                        .HasDatabaseName("ix_telemetry_records_device_id_device_time_is_sync_back");

                    b.ToTable("telemetry_records", "dev");
                });

            modelBuilder.Entity("Pico2WH.Pi5.IIoT.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("TenantScope")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tenant_scope");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", "dev");
                });

            modelBuilder.Entity("Pico2WH.Pi5.IIoT.Infrastructure.Persistence.Models.AppLogRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("device_id");

                    b.Property<DateTime?>("DeviceTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("device_time_utc");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_ip");

                    b.HasKey("Id")
                        .HasName("pk_app_logs");

                    b.HasIndex("Channel", "CreatedAtUtc")
                        .HasDatabaseName("ix_app_logs_channel_created_at_utc");

                    b.ToTable("app_logs", "dev");
                });

            modelBuilder.Entity("Pico2WH.Pi5.IIoT.Infrastructure.Persistence.Models.DeviceUiEventRecord", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EventId"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("channel");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("DeviceTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("device_time_utc");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("event_type");

                    b.Property<string>("EventValue")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_value");

                    b.Property<DateTime>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at_utc");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("site_id");

                    b.HasKey("EventId")
                        .HasName("pk_device_ui_events");

                    b.HasIndex("DeviceId", "DeviceTimeUtc")
                        .HasDatabaseName("ix_device_ui_events_device_id_device_time_utc");

                    b.HasIndex("SiteId", "DeviceId", "DeviceTimeUtc")
                        .HasDatabaseName("ix_device_ui_events_site_id_device_id_device_time_utc");

                    b.ToTable("device_ui_events", "dev");
                });

            modelBuilder.Entity("Pico2WH.Pi5.IIoT.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Pico2WH.Pi5.IIoT.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
